#!/usr/bin/env bash

# Project
PROJECT_NAME="embedded-linux-ota-platform"

# Yocto Build
YOCTO_BUILD_DIR="build"
YOCTO_MACHINE="raspberrypi3-64"
YOCTO_IMAGE="ota-platform-minimal-image"

# Mender Server
MENDER_SERVER_URL="https://docker.mender.io"

# Mender Server Host IP installed in the device /etc/hosts
MENDER_SERVER_HOST="docker.mender.io"
MENDER_SERVER_HOST_IP="192.168.0.88"

# CA certificate used by the device to verify the Mender endpoint
MENDER_SERVER_CRT="certificates/mender.crt"

# OTA Test Device
DEVICE_SSH_USER="root"
DEVICE_IP_ADDRESS="192.168.0.82"
DEVICE_MENDER_ID="b4285054-e943-40c5-817c-d63ba96d7d92"
